### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by psedlos** [dotnet/docs.pl-pl#168]
I somehow like you MS but you are not really good at translation. Please work a bit more on it before you start translating everything.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 80e0d8d3-ed1e-7e9d-d0dc-3d577c286f60
* Version Independent ID: 6961eaa7-db11-5794-746e-42fb6e4a964b
* Content: [Mod — Operator (Visual Basic)](https://docs.microsoft.com/pl-pl/dotnet/visual-basic/language-reference/operators/mod-operator#feedback)
* Content Source: [docs/visual-basic/language-reference/operators/mod-operator.md](https://github.com/dotnet/docs.pl-pl/blob/live/docs/visual-basic/language-reference/operators/mod-operator.md)
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by psedlos** [comment]
or at least give a chance to users to that they will be able to correct these translation so you might gain huge amount of manual human translation what could be great feed for machine learning..... but anyway I suggest to switch to google, sorry but they are mych batter

**Comment by LisandroSu** [comment]
Hello, @psedlos 
 
Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings. 

Also, there is a "Edit" link above the document's title. It will allow you to create a Pull Request with any modifications you may want to make to the file.
 
Kind regards, 
Microsoft DOCS International Team
