### ISSUE TITLE
Run not working

### ISSUE THREAD

**Issue by Morasiu** [dotnet/docs.pl-pl#188]
It shows:
```
(1,7): error CS1003: Syntax error, '(' expected
(1,13): error CS1026: ) expected
(1,1): error CS1513: } expected
(1,7): error CS0118: 'System' is a namespace but is used like a variable
```

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: fb6ba83b-2c7a-3732-604c-86fbdf699515
* Version Independent ID: ebc31d6d-d4e5-18df-8223-261a8b932951
* Content: [Operatory true i false - C# odwołania](https://docs.microsoft.com/pl-pl/dotnet/csharp/language-reference/keywords/true-false-operators)
* Content Source: [docs/csharp/language-reference/keywords/true-false-operators.md](https://github.com/dotnet/docs.pl-pl/blob/live/docs/csharp/language-reference/keywords/true-false-operators.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hello, @Morasiu 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by Morasiu** [comment]
Hi I've added screenshot to visualize what I'm talking about
