### ISSUE TITLE
How do you translate "dependency property"

### ISSUE THREAD

**Issue by MikDal002** [dotnet/docs.pl-pl#190]
Cześć, mam pytanie: w jaki sposób tłumaczycie wyrażenie „dependency property" w przypadku kiedy chodzi o właściwości kontrolek w WPF? Pytam się, ponieważ zlepka "właściiwość zależna" nie wiele mówi, a w końcu nie o to chodzi, aby tłumaczyć dla samego tłumaczenia, ale też aby  bylo to łatwiejsze do zrozumienia. 

-------------
Hello, 
I have one question: How do you translate "dependency property" sentence? I am asking because "właściwość zależna" doesn't mean a lot.

**Comment by CeciAc** [comment]
Hello, @MikDal002 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?

**Can you please provide an URL so we can check this issue?**
 
Kind regards,
Microsoft DOCS International Team

**Comment by MikDal002** [comment]
Hi @CeciAc,

I am not asking about a specific article, but in general: "how to translate «dependency property» phrase?". But if I have to point an article than for example https://docs.microsoft.com/pl-pl/dotnet/framework/wpf/advanced/xaml-overview-wpf#attached-properties-and-attached-events, especially here: "In WPF, most or all the attached properties are also implemented as **dependency properties**. ", what can be translated into: "W WPF większość lub wszystkie właściwości dołączane są również **właściwościami zależnymi**". The machine translation is "W WPF, większość lub wszystkie załączonych właściwości również są implementowane jako właściwości zależności." which sounds much worse. 
So, my question is: "how to properly translate «dependency property»".

**Comment by CeciAc** [comment]
Hello, @MikDal002 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @MikDal002

Thank you for your feedback.

From our linguists' feedback: _According to approved terminology "dependency property" is translated as "właściwość zależności". I find this translation correct in this context. ("właściwość zależna" is probably taken from machine translated content)._

Kind regards,
Microsoft DOCS International Team
