### ISSUE TITLE
Błędne tłumaczenia

### ISSUE THREAD

**Issue by skonieczny** [dotnet/docs.pl-pl#195]
Szczerze mówiąc trudniej mi zrozumieć stronę tak przetłumaczoną niż po angielsku bez tłumaczenia... Jeżeli celem tej strony jest rozśmieszenie użytkownika, to proponuję zamienić "jako" na "jajko".

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: b74b99ff-32f8-c2d1-0a62-5907985f591e
* Version Independent ID: 716a28dc-360e-2964-47f5-0ff18bb00b1c
* Content: [Formaty ścieżek plików w systemie Windows](https://docs.microsoft.com/pl-pl/dotnet/standard/io/file-path-formats#feedback)
* Content Source: [docs/standard/io/file-path-formats.md](https://github.com/dotnet/docs.pl-pl/blob/live/docs/standard/io/file-path-formats.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by skonieczny** [comment]
*użytkownika

**Comment by srvbpigh** [comment]
Hello, @skonieczny
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Witaj, @skonieczny
Dziękujemy za opinię. Ta strona została przetłumaczona maszynowo, a tekst tłumaczony tą metodą nie zawsze jest całkowicie zrozumiały. Niedawno po prawej stronie dodaliśmy opcję „Czytaj w języku angielskim”, która umożliwia zmianę wersji językowej na angielską bez konieczności zmiany ustawień języka. 
Pozdrawiamy, 
Międzynarodowy zespół witryny Microsoft DOCS
