### ISSUE TITLE
Not well translated sentences

### ISSUE THREAD

**Issue by weedget** [dotnet/docs.pl-pl#198]
On page
https://docs.microsoft.com/pl-pl/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=2
There is "@No__t-0" between 3rd and 4th example, instead of "@No__t-0" should be "&&"
and
https://docs.microsoft.com/pl-pl/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=3
Sentence: "W tym przykładzie istnieje jeden inny operator new. @No__t-0 po zmiennej counter jest operatorem przyrostu." is not correct in Polish.
It should be someting like:
"W tym przykładzie pojawia się nowy operator. Operator ++ użyty po zmiennej counter jest operatorem przyrostu."

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 77dec100-463d-f684-03b6-25f511d1d18f
* Version Independent ID: 27921da6-71b0-6dfc-2824-c84844152d8e
* Content: [Gałęzie i pętle — C# wprowadzenie do interaktywnego samouczka](https://docs.microsoft.com/pl-pl/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=7#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml](https://github.com/dotnet/docs.pl-pl/blob/live-sxs/docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @weedget
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by weedget** [comment]
@srvbpigh, @CeciAc  I found more similar issues, do you prefer to get them in one issue or maybe create fork and make a pull request with correct translations?

**Comment by CeciAc** [comment]
Hello, @weedget 

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/pl-pl/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=7#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
