### ISSUE TITLE
Syntax in the codebox is not highlighted

### ISSUE THREAD

**Issue by Nekuskus** [dotnet/docs.pl-pl#200]
The last codebox can be safely marked as simply C#. It doesn't contain any ASP.NET specific code yet ASP.NET mark prevents its syntax from being highlighted. 

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 2a5e0b56-4d67-b219-46fa-d837045e6612
* Version Independent ID: 50c65125-3700-c713-ede0-2204e09eb307
* Content: [Metody rozszerzenia — Przewodnik programowania w języku C#](https://docs.microsoft.com/pl-pl/dotnet/csharp/programming-guide/classes-and-structs/extension-methods)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/extension-methods.md](https://github.com/dotnet/docs.pl-pl/blob/live/docs/csharp/programming-guide/classes-and-structs/extension-methods.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @Nekuskus
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by mairaw** [comment]
I've opened a PR to fix the issue in the source.

**Comment by Nekuskus** [comment]
Thank you!
