### ISSUE TITLE
dotnet cli - Polish translation mistake

### ISSUE THREAD

**Issue by xearonet** [dotnet/docs.pl-pl#206]
Hi All,
There is contradiction in the description of the option in polish translation.
Option `--timeout` in english has clear and unambiguous description:

```
-t|--timeout <TIMEOUT>

Specifies the timeout for pushing to a server in seconds. Defaults to 300 seconds (5 minutes). Specifying 0 (zero seconds) applies the default value.
```

but polish version is confusing and has contradictory description of option:
```
-t|--timeout <TIMEOUT>

Określa limit czasu wypychania do serwera w sekundach. Wartość domyślna to 300 sekund (5 minut). Wartość domyślna to 0 (zero sekund).
```
should be:
```
-t|--timeout <TIMEOUT>

Określa limit czasu wypychania do serwera w sekundach. Wartość domyślna to 300 sekund (5 minut). Ustawienie 0 (zero sekund) spowoduje użycie wartości domyślnej.

```
Thanks
Damian

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: b363ab07-ea19-574f-e0db-25fd5702255d
* Version Independent ID: 6fa9479a-85db-5498-6b7e-2418fc7bac32
* Content: [polecenia wypychania NuGet dotnet - .NET CLI](https://docs.microsoft.com/pl-pl/dotnet/core/tools/dotnet-nuget-push)
* Content Source: [docs/core/tools/dotnet-nuget-push.md](https://github.com/dotnet/docs.pl-pl/blob/live/docs/core/tools/dotnet-nuget-push.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-cli**
* GitHub Login: @karann-msft
* Microsoft Alias: **tdykstra**

**Comment by BartoszKlonowski** [comment]
@v-radelg  I would like to work on this issue, so please assign me to this item.

**Comment by BartoszKlonowski** [comment]
@olprod Kind reminder - please assign me to this item and check the pull request linked.

**Comment by BartoszKlonowski** [comment]
@tdykstra @BillWagner Are you able to handle that? This issue can be closed.

**Comment by tdykstra** [comment]
@JasonCard

**Comment by JasonCard** [comment]
@tdykstra @BillWagner This is machine translation issue, but It seems that the original English text is also confusing and it should not have "(zero seconds)" in there? If the English text can be fixed by removing the "(zero seconds)" as "Specifying 0 applies the default value.", then it may translate better. We want to avoid having to manually fix machine translation unless it's necessary.

**Comment by tdykstra** [comment]
Remove text that was causing loc issues by tdykstra * Pull Request #23511 * dotnet/docs (github.com)<https://github.com/dotnet/docs/pull/23511>
