### ISSUE TITLE
IdentityServer is not an open-source anymore

### ISSUE THREAD

**Issue by yaroslavvasko** [dotnet/docs.pl-pl#208]
[Wprowadź tutaj swoją opinię]

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 188e28ad-73ce-658d-1712-f7b5e3ce61cf
* Version Independent ID: 52119533-ce08-ae89-21d0-fe36a8e3748d
* Content: [IdentityServer dla natywnych aplikacji w chmurze](https://docs.microsoft.com/pl-pl/dotnet/architecture/cloud-native/identity-server)
* Content Source: [docs/architecture/cloud-native/identity-server.md](https://github.com/dotnet/docs.pl-pl/blob/live/docs/architecture/cloud-native/identity-server.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by BartoszKlonowski** [comment]
@yaroslavvasko Are you sure? I'm able to still find all the *IdentityServer* repositories on GH: https://github.com/IdentityServer
It would be good if you could elaborate.

**Comment by yaroslavvasko** [comment]
@BartoszKlonowski  The creator of IdentityServer mentioned in his [blog](https://leastprivilege.com/2020/10/01/the-future-of-identityserver/):
> The current version (IdentityServer4 v4.x) will be the last version we work on as free open source. We will keep supporting IdentityServer4 until the end of life of .NET Core 3.1 in November 2022.

Also the license update mention in project [description](https://github.com/IdentityServer/IdentityServer4):
> As of Oct 1st 2020, we started a new company. All new feature work will happen in our new organization. The new Duende IdentityServer is available under both a FOSS (RPL) and a commercial license.

**Comment by BartoszKlonowski** [comment]
This issue can be closed by https://github.com/dotnet/docs/pull/23698

**Comment by BartoszKlonowski** [comment]
@BillWagner @gewarren @IEvangelist   Kind reminder - this issue can be closed, as it has been handled in the *dotnet/docs* repository and the translation should be fixed according to the base.

**Comment by gewarren** [comment]
Thank you @BartoszKlonowski
