### ISSUE TITLE
MT->HT when

### ISSUE THREAD

**Issue by warchlak** [dotnet/docs.pl-pl#29]
When the article has the right to get HT status?
Can users change it or only MS Team does it?

**Comment by perconey** [comment]
You can reach Microsoft Localization Team easier on https://twitter.com/docsmsft

**Comment by gosali** [comment]
@sara-nicolini

**Comment by CeciAc** [comment]
Hello, @warchlak 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

@nokura can you please get back to us with this feedback?
